/* automatically generated by rust-bindgen 0.72.1 */

pub const _GLIBCXX_CSTDDEF: u32 = 1;
pub const _GLIBCXX_CXX_CONFIG_H: u32 = 1;
pub const _GLIBCXX_RELEASE: u32 = 13;
pub const __GLIBCXX__: u32 = 20240904;
pub const _GLIBCXX_HAVE_ATTRIBUTE_VISIBILITY: u32 = 1;
pub const _GLIBCXX_USE_DEPRECATED: u32 = 1;
pub const _GLIBCXX_EXTERN_TEMPLATE: u32 = 1;
pub const _GLIBCXX_USE_DUAL_ABI: u32 = 1;
pub const _GLIBCXX_USE_CXX11_ABI: u32 = 1;
pub const _GLIBCXX_INLINE_VERSION: u32 = 0;
pub const _GLIBCXX_HAVE_IS_CONSTANT_EVALUATED: u32 = 1;
pub const _GLIBCXX_VERBOSE_ASSERT: u32 = 1;
pub const _GLIBCXX_USE_ALLOCATOR_NEW: u32 = 1;
pub const _GLIBCXX_OS_DEFINES: u32 = 1;
pub const __NO_CTYPE: u32 = 1;
pub const _FEATURES_H: u32 = 1;
pub const _ISOC95_SOURCE: u32 = 1;
pub const _ISOC99_SOURCE: u32 = 1;
pub const _ISOC11_SOURCE: u32 = 1;
pub const _ISOC2X_SOURCE: u32 = 1;
pub const _POSIX_SOURCE: u32 = 1;
pub const _POSIX_C_SOURCE: u32 = 200809;
pub const _XOPEN_SOURCE: u32 = 700;
pub const _XOPEN_SOURCE_EXTENDED: u32 = 1;
pub const _LARGEFILE64_SOURCE: u32 = 1;
pub const _DEFAULT_SOURCE: u32 = 1;
pub const _ATFILE_SOURCE: u32 = 1;
pub const _DYNAMIC_STACK_SIZE_SOURCE: u32 = 1;
pub const __GLIBC_USE_ISOC2X: u32 = 1;
pub const __USE_ISOC11: u32 = 1;
pub const __USE_ISOC99: u32 = 1;
pub const __USE_ISOC95: u32 = 1;
pub const __USE_ISOCXX11: u32 = 1;
pub const __USE_POSIX: u32 = 1;
pub const __USE_POSIX2: u32 = 1;
pub const __USE_POSIX199309: u32 = 1;
pub const __USE_POSIX199506: u32 = 1;
pub const __USE_XOPEN2K: u32 = 1;
pub const __USE_XOPEN2K8: u32 = 1;
pub const __USE_XOPEN: u32 = 1;
pub const __USE_XOPEN_EXTENDED: u32 = 1;
pub const __USE_UNIX98: u32 = 1;
pub const _LARGEFILE_SOURCE: u32 = 1;
pub const __USE_XOPEN2K8XSI: u32 = 1;
pub const __USE_XOPEN2KXSI: u32 = 1;
pub const __USE_LARGEFILE: u32 = 1;
pub const __USE_LARGEFILE64: u32 = 1;
pub const __WORDSIZE: u32 = 64;
pub const __WORDSIZE_TIME64_COMPAT32: u32 = 1;
pub const __SYSCALL_WORDSIZE: u32 = 64;
pub const __TIMESIZE: u32 = 64;
pub const __USE_MISC: u32 = 1;
pub const __USE_ATFILE: u32 = 1;
pub const __USE_DYNAMIC_STACK_SIZE: u32 = 1;
pub const __USE_GNU: u32 = 1;
pub const __USE_FORTIFY_LEVEL: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_GETS: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_SCANF: u32 = 0;
pub const __GLIBC_USE_C2X_STRTOL: u32 = 1;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_60559_BFP__: u32 = 201404;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_IEC_60559_COMPLEX__: u32 = 201404;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const __GNU_LIBRARY__: u32 = 6;
pub const __GLIBC__: u32 = 2;
pub const __GLIBC_MINOR__: u32 = 39;
pub const _SYS_CDEFS_H: u32 = 1;
pub const __glibc_c99_flexarr_available: u32 = 1;
pub const __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI: u32 = 0;
pub const __HAVE_GENERIC_SELECTION: u32 = 0;
pub const _GLIBCXX_HAVE_FLOAT128_MATH: u32 = 1;
pub const _GLIBCXX_GTHREAD_USE_WEAK: u32 = 0;
pub const _GLIBCXX_CPU_DEFINES: u32 = 1;
pub const _GLIBCXX_FAST_MATH: u32 = 0;
pub const _GLIBCXX_USE_FLOAT128: u32 = 1;
pub const _GLIBCXX_FLOAT_IS_IEEE_BINARY32: u32 = 1;
pub const _GLIBCXX_DOUBLE_IS_IEEE_BINARY64: u32 = 1;
pub const _GLIBCXX_HAVE_BUILTIN_HAS_UNIQ_OBJ_REP: u32 = 1;
pub const _GLIBCXX_HAVE_BUILTIN_IS_AGGREGATE: u32 = 1;
pub const _GLIBCXX_HAVE_BUILTIN_IS_SAME: u32 = 1;
pub const _GLIBCXX_HAVE_BUILTIN_LAUNDER: u32 = 1;
pub const _GLIBCXX_HAVE_ACOSF: u32 = 1;
pub const _GLIBCXX_HAVE_ACOSL: u32 = 1;
pub const _GLIBCXX_HAVE_ALIGNED_ALLOC: u32 = 1;
pub const _GLIBCXX_HAVE_ARC4RANDOM: u32 = 1;
pub const _GLIBCXX_HAVE_ARPA_INET_H: u32 = 1;
pub const _GLIBCXX_HAVE_ASINF: u32 = 1;
pub const _GLIBCXX_HAVE_ASINL: u32 = 1;
pub const _GLIBCXX_HAVE_AS_SYMVER_DIRECTIVE: u32 = 1;
pub const _GLIBCXX_HAVE_ATAN2F: u32 = 1;
pub const _GLIBCXX_HAVE_ATAN2L: u32 = 1;
pub const _GLIBCXX_HAVE_ATANF: u32 = 1;
pub const _GLIBCXX_HAVE_ATANL: u32 = 1;
pub const _GLIBCXX_HAVE_ATOMIC_LOCK_POLICY: u32 = 1;
pub const _GLIBCXX_HAVE_AT_QUICK_EXIT: u32 = 1;
pub const _GLIBCXX_HAVE_CEILF: u32 = 1;
pub const _GLIBCXX_HAVE_CEILL: u32 = 1;
pub const _GLIBCXX_HAVE_COMPLEX_H: u32 = 1;
pub const _GLIBCXX_HAVE_COSF: u32 = 1;
pub const _GLIBCXX_HAVE_COSHF: u32 = 1;
pub const _GLIBCXX_HAVE_COSHL: u32 = 1;
pub const _GLIBCXX_HAVE_COSL: u32 = 1;
pub const _GLIBCXX_HAVE_DECL_STRNLEN: u32 = 1;
pub const _GLIBCXX_HAVE_DIRENT_H: u32 = 1;
pub const _GLIBCXX_HAVE_DIRFD: u32 = 1;
pub const _GLIBCXX_HAVE_DLFCN_H: u32 = 1;
pub const _GLIBCXX_HAVE_ENDIAN_H: u32 = 1;
pub const _GLIBCXX_HAVE_EXCEPTION_PTR_SINCE_GCC46: u32 = 1;
pub const _GLIBCXX_HAVE_EXECINFO_H: u32 = 1;
pub const _GLIBCXX_HAVE_EXPF: u32 = 1;
pub const _GLIBCXX_HAVE_EXPL: u32 = 1;
pub const _GLIBCXX_HAVE_FABSF: u32 = 1;
pub const _GLIBCXX_HAVE_FABSL: u32 = 1;
pub const _GLIBCXX_HAVE_FCNTL_H: u32 = 1;
pub const _GLIBCXX_HAVE_FDOPENDIR: u32 = 1;
pub const _GLIBCXX_HAVE_FENV_H: u32 = 1;
pub const _GLIBCXX_HAVE_FINITE: u32 = 1;
pub const _GLIBCXX_HAVE_FINITEF: u32 = 1;
pub const _GLIBCXX_HAVE_FINITEL: u32 = 1;
pub const _GLIBCXX_HAVE_FLOAT_H: u32 = 1;
pub const _GLIBCXX_HAVE_FLOORF: u32 = 1;
pub const _GLIBCXX_HAVE_FLOORL: u32 = 1;
pub const _GLIBCXX_HAVE_FMODF: u32 = 1;
pub const _GLIBCXX_HAVE_FMODL: u32 = 1;
pub const _GLIBCXX_HAVE_FREXPF: u32 = 1;
pub const _GLIBCXX_HAVE_FREXPL: u32 = 1;
pub const _GLIBCXX_HAVE_GETENTROPY: u32 = 1;
pub const _GLIBCXX_HAVE_GETIPINFO: u32 = 1;
pub const _GLIBCXX_HAVE_GETS: u32 = 1;
pub const _GLIBCXX_HAVE_HYPOT: u32 = 1;
pub const _GLIBCXX_HAVE_HYPOTF: u32 = 1;
pub const _GLIBCXX_HAVE_HYPOTL: u32 = 1;
pub const _GLIBCXX_HAVE_ICONV: u32 = 1;
pub const _GLIBCXX_HAVE_INTTYPES_H: u32 = 1;
pub const _GLIBCXX_HAVE_ISINFF: u32 = 1;
pub const _GLIBCXX_HAVE_ISINFL: u32 = 1;
pub const _GLIBCXX_HAVE_ISNANF: u32 = 1;
pub const _GLIBCXX_HAVE_ISNANL: u32 = 1;
pub const _GLIBCXX_HAVE_ISWBLANK: u32 = 1;
pub const _GLIBCXX_HAVE_LC_MESSAGES: u32 = 1;
pub const _GLIBCXX_HAVE_LDEXPF: u32 = 1;
pub const _GLIBCXX_HAVE_LDEXPL: u32 = 1;
pub const _GLIBCXX_HAVE_LIBINTL_H: u32 = 1;
pub const _GLIBCXX_HAVE_LIMIT_AS: u32 = 1;
pub const _GLIBCXX_HAVE_LIMIT_DATA: u32 = 1;
pub const _GLIBCXX_HAVE_LIMIT_FSIZE: u32 = 1;
pub const _GLIBCXX_HAVE_LIMIT_RSS: u32 = 1;
pub const _GLIBCXX_HAVE_LIMIT_VMEM: u32 = 0;
pub const _GLIBCXX_HAVE_LINK: u32 = 1;
pub const _GLIBCXX_HAVE_LINK_H: u32 = 1;
pub const _GLIBCXX_HAVE_LINUX_FUTEX: u32 = 1;
pub const _GLIBCXX_HAVE_LINUX_RANDOM_H: u32 = 1;
pub const _GLIBCXX_HAVE_LINUX_TYPES_H: u32 = 1;
pub const _GLIBCXX_HAVE_LOCALE_H: u32 = 1;
pub const _GLIBCXX_HAVE_LOG10F: u32 = 1;
pub const _GLIBCXX_HAVE_LOG10L: u32 = 1;
pub const _GLIBCXX_HAVE_LOGF: u32 = 1;
pub const _GLIBCXX_HAVE_LOGL: u32 = 1;
pub const _GLIBCXX_HAVE_MBSTATE_T: u32 = 1;
pub const _GLIBCXX_HAVE_MEMALIGN: u32 = 1;
pub const _GLIBCXX_HAVE_MEMORY_H: u32 = 1;
pub const _GLIBCXX_HAVE_MODF: u32 = 1;
pub const _GLIBCXX_HAVE_MODFF: u32 = 1;
pub const _GLIBCXX_HAVE_MODFL: u32 = 1;
pub const _GLIBCXX_HAVE_NETDB_H: u32 = 1;
pub const _GLIBCXX_HAVE_NETINET_IN_H: u32 = 1;
pub const _GLIBCXX_HAVE_NETINET_TCP_H: u32 = 1;
pub const _GLIBCXX_HAVE_OPENAT: u32 = 1;
pub const _GLIBCXX_HAVE_POLL: u32 = 1;
pub const _GLIBCXX_HAVE_POLL_H: u32 = 1;
pub const _GLIBCXX_HAVE_POSIX_MEMALIGN: u32 = 1;
pub const _GLIBCXX_HAVE_POSIX_SEMAPHORE: u32 = 1;
pub const _GLIBCXX_HAVE_POWF: u32 = 1;
pub const _GLIBCXX_HAVE_POWL: u32 = 1;
pub const _GLIBCXX_HAVE_QUICK_EXIT: u32 = 1;
pub const _GLIBCXX_HAVE_READLINK: u32 = 1;
pub const _GLIBCXX_HAVE_SECURE_GETENV: u32 = 1;
pub const _GLIBCXX_HAVE_SETENV: u32 = 1;
pub const _GLIBCXX_HAVE_SINCOS: u32 = 1;
pub const _GLIBCXX_HAVE_SINCOSF: u32 = 1;
pub const _GLIBCXX_HAVE_SINCOSL: u32 = 1;
pub const _GLIBCXX_HAVE_SINF: u32 = 1;
pub const _GLIBCXX_HAVE_SINHF: u32 = 1;
pub const _GLIBCXX_HAVE_SINHL: u32 = 1;
pub const _GLIBCXX_HAVE_SINL: u32 = 1;
pub const _GLIBCXX_HAVE_SOCKATMARK: u32 = 1;
pub const _GLIBCXX_HAVE_SQRTF: u32 = 1;
pub const _GLIBCXX_HAVE_SQRTL: u32 = 1;
pub const _GLIBCXX_HAVE_STACKTRACE: u32 = 1;
pub const _GLIBCXX_HAVE_STDALIGN_H: u32 = 1;
pub const _GLIBCXX_HAVE_STDBOOL_H: u32 = 1;
pub const _GLIBCXX_HAVE_STDINT_H: u32 = 1;
pub const _GLIBCXX_HAVE_STDLIB_H: u32 = 1;
pub const _GLIBCXX_HAVE_STRERROR_L: u32 = 1;
pub const _GLIBCXX_HAVE_STRERROR_R: u32 = 1;
pub const _GLIBCXX_HAVE_STRINGS_H: u32 = 1;
pub const _GLIBCXX_HAVE_STRING_H: u32 = 1;
pub const _GLIBCXX_HAVE_STRTOF: u32 = 1;
pub const _GLIBCXX_HAVE_STRTOLD: u32 = 1;
pub const _GLIBCXX_HAVE_STRUCT_DIRENT_D_TYPE: u32 = 1;
pub const _GLIBCXX_HAVE_STRXFRM_L: u32 = 1;
pub const _GLIBCXX_HAVE_SYMLINK: u32 = 1;
pub const _GLIBCXX_HAVE_SYMVER_SYMBOL_RENAMING_RUNTIME_SUPPORT: u32 = 1;
pub const _GLIBCXX_HAVE_SYS_IOCTL_H: u32 = 1;
pub const _GLIBCXX_HAVE_SYS_IPC_H: u32 = 1;
pub const _GLIBCXX_HAVE_SYS_MMAN_H: u32 = 1;
pub const _GLIBCXX_HAVE_SYS_PARAM_H: u32 = 1;
pub const _GLIBCXX_HAVE_SYS_RESOURCE_H: u32 = 1;
pub const _GLIBCXX_HAVE_SYS_SDT_H: u32 = 1;
pub const _GLIBCXX_HAVE_SYS_SEM_H: u32 = 1;
pub const _GLIBCXX_HAVE_SYS_SOCKET_H: u32 = 1;
pub const _GLIBCXX_HAVE_SYS_STATVFS_H: u32 = 1;
pub const _GLIBCXX_HAVE_SYS_STAT_H: u32 = 1;
pub const _GLIBCXX_HAVE_SYS_SYSINFO_H: u32 = 1;
pub const _GLIBCXX_HAVE_SYS_TIME_H: u32 = 1;
pub const _GLIBCXX_HAVE_SYS_TYPES_H: u32 = 1;
pub const _GLIBCXX_HAVE_SYS_UIO_H: u32 = 1;
pub const _GLIBCXX_HAVE_S_ISREG: u32 = 1;
pub const _GLIBCXX_HAVE_TANF: u32 = 1;
pub const _GLIBCXX_HAVE_TANHF: u32 = 1;
pub const _GLIBCXX_HAVE_TANHL: u32 = 1;
pub const _GLIBCXX_HAVE_TANL: u32 = 1;
pub const _GLIBCXX_HAVE_TGMATH_H: u32 = 1;
pub const _GLIBCXX_HAVE_TIMESPEC_GET: u32 = 1;
pub const _GLIBCXX_HAVE_TLS: u32 = 1;
pub const _GLIBCXX_HAVE_TRUNCATE: u32 = 1;
pub const _GLIBCXX_HAVE_UCHAR_H: u32 = 1;
pub const _GLIBCXX_HAVE_UNISTD_H: u32 = 1;
pub const _GLIBCXX_HAVE_UNLINKAT: u32 = 1;
pub const _GLIBCXX_HAVE_USELOCALE: u32 = 1;
pub const _GLIBCXX_HAVE_UTIME_H: u32 = 1;
pub const _GLIBCXX_HAVE_VFWSCANF: u32 = 1;
pub const _GLIBCXX_HAVE_VSWSCANF: u32 = 1;
pub const _GLIBCXX_HAVE_VWSCANF: u32 = 1;
pub const _GLIBCXX_HAVE_WCHAR_H: u32 = 1;
pub const _GLIBCXX_HAVE_WCSTOF: u32 = 1;
pub const _GLIBCXX_HAVE_WCTYPE_H: u32 = 1;
pub const _GLIBCXX_HAVE_WRITEV: u32 = 1;
pub const _GLIBCXX_HAVE___CXA_THREAD_ATEXIT_IMPL: u32 = 1;
pub const _GLIBCXX_LT_OBJDIR: &[u8; 7] = b".libs/\0";
pub const _GLIBCXX_PACKAGE_BUGREPORT: &[u8; 1] = b"\0";
pub const _GLIBCXX_PACKAGE_NAME: &[u8; 15] = b"package-unused\0";
pub const _GLIBCXX_PACKAGE_STRING: &[u8; 30] = b"package-unused version-unused\0";
pub const _GLIBCXX_PACKAGE_TARNAME: &[u8; 10] = b"libstdc++\0";
pub const _GLIBCXX_PACKAGE_URL: &[u8; 1] = b"\0";
pub const _GLIBCXX_PACKAGE__GLIBCXX_VERSION: &[u8; 15] = b"version-unused\0";
pub const _GLIBCXX_STDC_HEADERS: u32 = 1;
pub const _GLIBCXX_DARWIN_USE_64_BIT_INODE: u32 = 1;
pub const _GLIBCXX11_USE_C99_COMPLEX: u32 = 1;
pub const _GLIBCXX11_USE_C99_MATH: u32 = 1;
pub const _GLIBCXX11_USE_C99_STDIO: u32 = 1;
pub const _GLIBCXX11_USE_C99_STDLIB: u32 = 1;
pub const _GLIBCXX11_USE_C99_WCHAR: u32 = 1;
pub const _GLIBCXX98_USE_C99_COMPLEX: u32 = 1;
pub const _GLIBCXX98_USE_C99_MATH: u32 = 1;
pub const _GLIBCXX98_USE_C99_STDIO: u32 = 1;
pub const _GLIBCXX98_USE_C99_STDLIB: u32 = 1;
pub const _GLIBCXX98_USE_C99_WCHAR: u32 = 1;
pub const _GLIBCXX_ATOMIC_BUILTINS: u32 = 1;
pub const _GLIBCXX_CAN_ALIGNAS_DESTRUCTIVE_SIZE: u32 = 1;
pub const _GLIBCXX_FULLY_DYNAMIC_STRING: u32 = 0;
pub const _GLIBCXX_HAS_GTHREADS: u32 = 1;
pub const _GLIBCXX_RES_LIMITS: u32 = 1;
pub const _GLIBCXX_STATIC_TZDATA: u32 = 1;
pub const _GLIBCXX_STDIO_EOF: i32 = -1;
pub const _GLIBCXX_STDIO_SEEK_CUR: u32 = 1;
pub const _GLIBCXX_STDIO_SEEK_END: u32 = 2;
pub const _GLIBCXX_SYMVER: u32 = 1;
pub const _GLIBCXX_SYMVER_GNU: u32 = 1;
pub const _GLIBCXX_USE_C11_UCHAR_CXX11: u32 = 1;
pub const _GLIBCXX_USE_C99: u32 = 1;
pub const _GLIBCXX_USE_C99_COMPLEX_TR1: u32 = 1;
pub const _GLIBCXX_USE_C99_CTYPE_TR1: u32 = 1;
pub const _GLIBCXX_USE_C99_FENV_TR1: u32 = 1;
pub const _GLIBCXX_USE_C99_INTTYPES_TR1: u32 = 1;
pub const _GLIBCXX_USE_C99_INTTYPES_WCHAR_T_TR1: u32 = 1;
pub const _GLIBCXX_USE_C99_MATH_TR1: u32 = 1;
pub const _GLIBCXX_USE_C99_STDINT_TR1: u32 = 1;
pub const _GLIBCXX_USE_CHDIR: u32 = 1;
pub const _GLIBCXX_USE_CHMOD: u32 = 1;
pub const _GLIBCXX_USE_CLOCK_MONOTONIC: u32 = 1;
pub const _GLIBCXX_USE_CLOCK_REALTIME: u32 = 1;
pub const _GLIBCXX_USE_DECIMAL_FLOAT: u32 = 1;
pub const _GLIBCXX_USE_DEV_RANDOM: u32 = 1;
pub const _GLIBCXX_USE_FCHMOD: u32 = 1;
pub const _GLIBCXX_USE_FCHMODAT: u32 = 1;
pub const _GLIBCXX_USE_FSEEKO_FTELLO: u32 = 1;
pub const _GLIBCXX_USE_GETCWD: u32 = 1;
pub const _GLIBCXX_USE_GETTIMEOFDAY: u32 = 1;
pub const _GLIBCXX_USE_GET_NPROCS: u32 = 1;
pub const _GLIBCXX_USE_INIT_PRIORITY_ATTRIBUTE: u32 = 1;
pub const _GLIBCXX_USE_LFS: u32 = 1;
pub const _GLIBCXX_USE_LONG_LONG: u32 = 1;
pub const _GLIBCXX_USE_LSTAT: u32 = 1;
pub const _GLIBCXX_USE_MKDIR: u32 = 1;
pub const _GLIBCXX_USE_NANOSLEEP: u32 = 1;
pub const _GLIBCXX_USE_NLS: u32 = 1;
pub const _GLIBCXX_USE_PTHREAD_COND_CLOCKWAIT: u32 = 1;
pub const _GLIBCXX_USE_PTHREAD_MUTEX_CLOCKLOCK: u32 = 1;
pub const _GLIBCXX_USE_PTHREAD_RWLOCK_CLOCKLOCK: u32 = 1;
pub const _GLIBCXX_USE_PTHREAD_RWLOCK_T: u32 = 1;
pub const _GLIBCXX_USE_RANDOM_TR1: u32 = 1;
pub const _GLIBCXX_USE_REALPATH: u32 = 1;
pub const _GLIBCXX_USE_SCHED_YIELD: u32 = 1;
pub const _GLIBCXX_USE_SC_NPROCESSORS_ONLN: u32 = 1;
pub const _GLIBCXX_USE_SENDFILE: u32 = 1;
pub const _GLIBCXX_USE_ST_MTIM: u32 = 1;
pub const _GLIBCXX_USE_TMPNAM: u32 = 1;
pub const _GLIBCXX_USE_UCHAR_C8RTOMB_MBRTOC8_CXX20: u32 = 1;
pub const _GLIBCXX_USE_UCHAR_C8RTOMB_MBRTOC8_FCHAR8_T: u32 = 1;
pub const _GLIBCXX_USE_UTIME: u32 = 1;
pub const _GLIBCXX_USE_UTIMENSAT: u32 = 1;
pub const _GLIBCXX_USE_WCHAR_T: u32 = 1;
pub const _GLIBCXX_VERBOSE: u32 = 1;
pub const _GLIBCXX_X86_RDRAND: u32 = 1;
pub const _GLIBCXX_X86_RDSEED: u32 = 1;
pub const _GLIBCXX_ZONEINFO_DIR: &[u8; 20] = b"/usr/share/zoneinfo\0";
pub const _GTHREAD_USE_MUTEX_TIMEDLOCK: u32 = 1;
pub const _GLIBCXX_CSTDINT: u32 = 1;
pub const _STDINT_H: u32 = 1;
pub const __GLIBC_USE_LIB_EXT2: u32 = 1;
pub const __GLIBC_USE_IEC_60559_BFP_EXT: u32 = 1;
pub const __GLIBC_USE_IEC_60559_BFP_EXT_C2X: u32 = 1;
pub const __GLIBC_USE_IEC_60559_EXT: u32 = 1;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT: u32 = 1;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT_C2X: u32 = 1;
pub const __GLIBC_USE_IEC_60559_TYPES_EXT: u32 = 1;
pub const _BITS_TYPES_H: u32 = 1;
pub const _BITS_TYPESIZES_H: u32 = 1;
pub const __OFF_T_MATCHES_OFF64_T: u32 = 1;
pub const __INO_T_MATCHES_INO64_T: u32 = 1;
pub const __RLIM_T_MATCHES_RLIM64_T: u32 = 1;
pub const __STATFS_MATCHES_STATFS64: u32 = 1;
pub const __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64: u32 = 1;
pub const __FD_SETSIZE: u32 = 1024;
pub const _BITS_TIME64_H: u32 = 1;
pub const _BITS_WCHAR_H: u32 = 1;
pub const _BITS_STDINT_INTN_H: u32 = 1;
pub const _BITS_STDINT_UINTN_H: u32 = 1;
pub const _BITS_STDINT_LEAST_H: u32 = 1;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i64 = -9223372036854775808;
pub const INT_FAST32_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u64 = 9223372036854775807;
pub const INT_FAST32_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: i32 = -1;
pub const UINT_FAST32_MAX: i32 = -1;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const UINTPTR_MAX: i32 = -1;
pub const PTRDIFF_MIN: i64 = -9223372036854775808;
pub const PTRDIFF_MAX: u64 = 9223372036854775807;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const SIZE_MAX: i32 = -1;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 4294967295;
pub const INT8_WIDTH: u32 = 8;
pub const UINT8_WIDTH: u32 = 8;
pub const INT16_WIDTH: u32 = 16;
pub const UINT16_WIDTH: u32 = 16;
pub const INT32_WIDTH: u32 = 32;
pub const UINT32_WIDTH: u32 = 32;
pub const INT64_WIDTH: u32 = 64;
pub const UINT64_WIDTH: u32 = 64;
pub const INT_LEAST8_WIDTH: u32 = 8;
pub const UINT_LEAST8_WIDTH: u32 = 8;
pub const INT_LEAST16_WIDTH: u32 = 16;
pub const UINT_LEAST16_WIDTH: u32 = 16;
pub const INT_LEAST32_WIDTH: u32 = 32;
pub const UINT_LEAST32_WIDTH: u32 = 32;
pub const INT_LEAST64_WIDTH: u32 = 64;
pub const UINT_LEAST64_WIDTH: u32 = 64;
pub const INT_FAST8_WIDTH: u32 = 8;
pub const UINT_FAST8_WIDTH: u32 = 8;
pub const INT_FAST16_WIDTH: u32 = 64;
pub const UINT_FAST16_WIDTH: u32 = 64;
pub const INT_FAST32_WIDTH: u32 = 64;
pub const UINT_FAST32_WIDTH: u32 = 64;
pub const INT_FAST64_WIDTH: u32 = 64;
pub const UINT_FAST64_WIDTH: u32 = 64;
pub const INTPTR_WIDTH: u32 = 64;
pub const UINTPTR_WIDTH: u32 = 64;
pub const INTMAX_WIDTH: u32 = 64;
pub const UINTMAX_WIDTH: u32 = 64;
pub const PTRDIFF_WIDTH: u32 = 64;
pub const SIG_ATOMIC_WIDTH: u32 = 32;
pub const SIZE_WIDTH: u32 = 64;
pub const WCHAR_WIDTH: u32 = 32;
pub const WINT_WIDTH: u32 = 32;
pub type std_nullptr_t = *const ::std::os::raw::c_void;
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct max_align_t {
    pub __clang_max_align_nonce1: ::std::os::raw::c_longlong,
    pub __bindgen_padding_0: u64,
    pub __clang_max_align_nonce2: u128,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of max_align_t"][::std::mem::size_of::<max_align_t>() - 32usize];
    ["Alignment of max_align_t"][::std::mem::align_of::<max_align_t>() - 16usize];
    ["Offset of field: max_align_t::__clang_max_align_nonce1"]
        [::std::mem::offset_of!(max_align_t, __clang_max_align_nonce1) - 0usize];
    ["Offset of field: max_align_t::__clang_max_align_nonce2"]
        [::std::mem::offset_of!(max_align_t, __clang_max_align_nonce2) - 16usize];
};
pub type __u_char = ::std::os::raw::c_uchar;
pub type __u_short = ::std::os::raw::c_ushort;
pub type __u_int = ::std::os::raw::c_uint;
pub type __u_long = ::std::os::raw::c_ulong;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_long;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type __int_least8_t = __int8_t;
pub type __uint_least8_t = __uint8_t;
pub type __int_least16_t = __int16_t;
pub type __uint_least16_t = __uint16_t;
pub type __int_least32_t = __int32_t;
pub type __uint_least32_t = __uint32_t;
pub type __int_least64_t = __int64_t;
pub type __uint_least64_t = __uint64_t;
pub type __quad_t = ::std::os::raw::c_long;
pub type __u_quad_t = ::std::os::raw::c_ulong;
pub type __intmax_t = ::std::os::raw::c_long;
pub type __uintmax_t = ::std::os::raw::c_ulong;
pub type __dev_t = ::std::os::raw::c_ulong;
pub type __uid_t = ::std::os::raw::c_uint;
pub type __gid_t = ::std::os::raw::c_uint;
pub type __ino_t = ::std::os::raw::c_ulong;
pub type __ino64_t = ::std::os::raw::c_ulong;
pub type __mode_t = ::std::os::raw::c_uint;
pub type __nlink_t = ::std::os::raw::c_ulong;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type __pid_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __fsid_t {
    pub __val: [::std::os::raw::c_int; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __fsid_t"][::std::mem::size_of::<__fsid_t>() - 8usize];
    ["Alignment of __fsid_t"][::std::mem::align_of::<__fsid_t>() - 4usize];
    ["Offset of field: __fsid_t::__val"][::std::mem::offset_of!(__fsid_t, __val) - 0usize];
};
pub type __clock_t = ::std::os::raw::c_long;
pub type __rlim_t = ::std::os::raw::c_ulong;
pub type __rlim64_t = ::std::os::raw::c_ulong;
pub type __id_t = ::std::os::raw::c_uint;
pub type __time_t = ::std::os::raw::c_long;
pub type __useconds_t = ::std::os::raw::c_uint;
pub type __suseconds_t = ::std::os::raw::c_long;
pub type __suseconds64_t = ::std::os::raw::c_long;
pub type __daddr_t = ::std::os::raw::c_int;
pub type __key_t = ::std::os::raw::c_int;
pub type __clockid_t = ::std::os::raw::c_int;
pub type __timer_t = *mut ::std::os::raw::c_void;
pub type __blksize_t = ::std::os::raw::c_long;
pub type __blkcnt_t = ::std::os::raw::c_long;
pub type __blkcnt64_t = ::std::os::raw::c_long;
pub type __fsblkcnt_t = ::std::os::raw::c_ulong;
pub type __fsblkcnt64_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt64_t = ::std::os::raw::c_ulong;
pub type __fsword_t = ::std::os::raw::c_long;
pub type __ssize_t = ::std::os::raw::c_long;
pub type __syscall_slong_t = ::std::os::raw::c_long;
pub type __syscall_ulong_t = ::std::os::raw::c_ulong;
pub type __loff_t = __off64_t;
pub type __caddr_t = *mut ::std::os::raw::c_char;
pub type __intptr_t = ::std::os::raw::c_long;
pub type __socklen_t = ::std::os::raw::c_uint;
pub type __sig_atomic_t = ::std::os::raw::c_int;
pub type int_least8_t = __int_least8_t;
pub type int_least16_t = __int_least16_t;
pub type int_least32_t = __int_least32_t;
pub type int_least64_t = __int_least64_t;
pub type uint_least8_t = __uint_least8_t;
pub type uint_least16_t = __uint_least16_t;
pub type uint_least32_t = __uint_least32_t;
pub type uint_least64_t = __uint_least64_t;
pub type int_fast8_t = ::std::os::raw::c_schar;
pub type int_fast16_t = ::std::os::raw::c_long;
pub type int_fast32_t = ::std::os::raw::c_long;
pub type int_fast64_t = ::std::os::raw::c_long;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_ulong;
pub type uint_fast32_t = ::std::os::raw::c_ulong;
pub type uint_fast64_t = ::std::os::raw::c_ulong;
pub type intmax_t = __intmax_t;
pub type uintmax_t = __uintmax_t;
pub type size_tp = u64;
pub type window_tp = u64;
pub type rate_tp = u64;
pub type time_tp = i32;
pub type count_tp = i32;
pub const ecn_tp_ecn_not_ect: ecn_tp = 0;
pub const ecn_tp_ecn_l4s_id: ecn_tp = 1;
pub const ecn_tp_ecn_ect0: ecn_tp = 2;
pub const ecn_tp_ecn_ce: ecn_tp = 3;
pub type ecn_tp = u8;
pub type fps_tp = u8;
pub type prob_tp = i64;
pub const cs_tp_cs_init: cs_tp = 0;
pub const cs_tp_cs_cong_avoid: cs_tp = 1;
pub const cs_tp_cs_in_loss: cs_tp = 2;
pub const cs_tp_cs_in_cwr: cs_tp = 3;
pub type cs_tp = ::std::os::raw::c_uint;
pub const cca_tp_cca_prague_win: cca_tp = 0;
pub const cca_tp_cca_prague_rate: cca_tp = 1;
pub type cca_tp = ::std::os::raw::c_uint;
pub const PRAGUE_INITWIN: count_tp = 10;
pub const PRAGUE_MINMTU: size_tp = 150;
pub const PRAGUE_INITMTU: size_tp = 1400;
pub const PRAGUE_INITRATE: rate_tp = 12500;
pub const PRAGUE_MINRATE: rate_tp = 12500;
pub const PRAGUE_MAXRATE: rate_tp = 12500000000;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PragueState {
    pub m_start_ref: time_tp,
    pub m_init_rate: rate_tp,
    pub m_init_window: window_tp,
    pub m_min_rate: rate_tp,
    pub m_max_rate: rate_tp,
    pub m_max_packet_size: size_tp,
    pub m_frame_interval: time_tp,
    pub m_frame_budget: time_tp,
    pub m_ts_remote: time_tp,
    pub m_rtt: time_tp,
    pub m_srtt: time_tp,
    pub m_vrtt: time_tp,
    pub m_r_prev_ts: time_tp,
    pub m_r_packets_received: count_tp,
    pub m_r_packets_CE: count_tp,
    pub m_r_packets_lost: count_tp,
    pub m_r_error_L4S: bool,
    pub m_cc_ts: time_tp,
    pub m_packets_received: count_tp,
    pub m_packets_CE: count_tp,
    pub m_packets_lost: count_tp,
    pub m_packets_sent: count_tp,
    pub m_error_L4S: bool,
    pub m_alpha_ts: time_tp,
    pub m_alpha_packets_received: count_tp,
    pub m_alpha_packets_CE: count_tp,
    pub m_alpha_packets_lost: count_tp,
    pub m_alpha_packets_sent: count_tp,
    pub m_loss_ts: time_tp,
    pub m_loss_cca: cca_tp,
    pub m_lost_window: window_tp,
    pub m_lost_rate: rate_tp,
    pub m_lost_rtts_to_growth: count_tp,
    pub m_loss_packets_lost: count_tp,
    pub m_loss_packets_sent: count_tp,
    pub m_cwr_ts: time_tp,
    pub m_cwr_packets_sent: count_tp,
    pub m_cc_state: cs_tp,
    pub m_cca_mode: cca_tp,
    pub m_rtts_to_growth: count_tp,
    pub m_alpha: prob_tp,
    pub m_pacing_rate: rate_tp,
    pub m_fractional_window: window_tp,
    pub m_packet_burst: count_tp,
    pub m_packet_size: size_tp,
    pub m_packet_window: count_tp,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PragueState"][::std::mem::size_of::<PragueState>() - 240usize];
    ["Alignment of PragueState"][::std::mem::align_of::<PragueState>() - 8usize];
    ["Offset of field: PragueState::m_start_ref"]
        [::std::mem::offset_of!(PragueState, m_start_ref) - 0usize];
    ["Offset of field: PragueState::m_init_rate"]
        [::std::mem::offset_of!(PragueState, m_init_rate) - 8usize];
    ["Offset of field: PragueState::m_init_window"]
        [::std::mem::offset_of!(PragueState, m_init_window) - 16usize];
    ["Offset of field: PragueState::m_min_rate"]
        [::std::mem::offset_of!(PragueState, m_min_rate) - 24usize];
    ["Offset of field: PragueState::m_max_rate"]
        [::std::mem::offset_of!(PragueState, m_max_rate) - 32usize];
    ["Offset of field: PragueState::m_max_packet_size"]
        [::std::mem::offset_of!(PragueState, m_max_packet_size) - 40usize];
    ["Offset of field: PragueState::m_frame_interval"]
        [::std::mem::offset_of!(PragueState, m_frame_interval) - 48usize];
    ["Offset of field: PragueState::m_frame_budget"]
        [::std::mem::offset_of!(PragueState, m_frame_budget) - 52usize];
    ["Offset of field: PragueState::m_ts_remote"]
        [::std::mem::offset_of!(PragueState, m_ts_remote) - 56usize];
    ["Offset of field: PragueState::m_rtt"][::std::mem::offset_of!(PragueState, m_rtt) - 60usize];
    ["Offset of field: PragueState::m_srtt"][::std::mem::offset_of!(PragueState, m_srtt) - 64usize];
    ["Offset of field: PragueState::m_vrtt"][::std::mem::offset_of!(PragueState, m_vrtt) - 68usize];
    ["Offset of field: PragueState::m_r_prev_ts"]
        [::std::mem::offset_of!(PragueState, m_r_prev_ts) - 72usize];
    ["Offset of field: PragueState::m_r_packets_received"]
        [::std::mem::offset_of!(PragueState, m_r_packets_received) - 76usize];
    ["Offset of field: PragueState::m_r_packets_CE"]
        [::std::mem::offset_of!(PragueState, m_r_packets_CE) - 80usize];
    ["Offset of field: PragueState::m_r_packets_lost"]
        [::std::mem::offset_of!(PragueState, m_r_packets_lost) - 84usize];
    ["Offset of field: PragueState::m_r_error_L4S"]
        [::std::mem::offset_of!(PragueState, m_r_error_L4S) - 88usize];
    ["Offset of field: PragueState::m_cc_ts"]
        [::std::mem::offset_of!(PragueState, m_cc_ts) - 92usize];
    ["Offset of field: PragueState::m_packets_received"]
        [::std::mem::offset_of!(PragueState, m_packets_received) - 96usize];
    ["Offset of field: PragueState::m_packets_CE"]
        [::std::mem::offset_of!(PragueState, m_packets_CE) - 100usize];
    ["Offset of field: PragueState::m_packets_lost"]
        [::std::mem::offset_of!(PragueState, m_packets_lost) - 104usize];
    ["Offset of field: PragueState::m_packets_sent"]
        [::std::mem::offset_of!(PragueState, m_packets_sent) - 108usize];
    ["Offset of field: PragueState::m_error_L4S"]
        [::std::mem::offset_of!(PragueState, m_error_L4S) - 112usize];
    ["Offset of field: PragueState::m_alpha_ts"]
        [::std::mem::offset_of!(PragueState, m_alpha_ts) - 116usize];
    ["Offset of field: PragueState::m_alpha_packets_received"]
        [::std::mem::offset_of!(PragueState, m_alpha_packets_received) - 120usize];
    ["Offset of field: PragueState::m_alpha_packets_CE"]
        [::std::mem::offset_of!(PragueState, m_alpha_packets_CE) - 124usize];
    ["Offset of field: PragueState::m_alpha_packets_lost"]
        [::std::mem::offset_of!(PragueState, m_alpha_packets_lost) - 128usize];
    ["Offset of field: PragueState::m_alpha_packets_sent"]
        [::std::mem::offset_of!(PragueState, m_alpha_packets_sent) - 132usize];
    ["Offset of field: PragueState::m_loss_ts"]
        [::std::mem::offset_of!(PragueState, m_loss_ts) - 136usize];
    ["Offset of field: PragueState::m_loss_cca"]
        [::std::mem::offset_of!(PragueState, m_loss_cca) - 140usize];
    ["Offset of field: PragueState::m_lost_window"]
        [::std::mem::offset_of!(PragueState, m_lost_window) - 144usize];
    ["Offset of field: PragueState::m_lost_rate"]
        [::std::mem::offset_of!(PragueState, m_lost_rate) - 152usize];
    ["Offset of field: PragueState::m_lost_rtts_to_growth"]
        [::std::mem::offset_of!(PragueState, m_lost_rtts_to_growth) - 160usize];
    ["Offset of field: PragueState::m_loss_packets_lost"]
        [::std::mem::offset_of!(PragueState, m_loss_packets_lost) - 164usize];
    ["Offset of field: PragueState::m_loss_packets_sent"]
        [::std::mem::offset_of!(PragueState, m_loss_packets_sent) - 168usize];
    ["Offset of field: PragueState::m_cwr_ts"]
        [::std::mem::offset_of!(PragueState, m_cwr_ts) - 172usize];
    ["Offset of field: PragueState::m_cwr_packets_sent"]
        [::std::mem::offset_of!(PragueState, m_cwr_packets_sent) - 176usize];
    ["Offset of field: PragueState::m_cc_state"]
        [::std::mem::offset_of!(PragueState, m_cc_state) - 180usize];
    ["Offset of field: PragueState::m_cca_mode"]
        [::std::mem::offset_of!(PragueState, m_cca_mode) - 184usize];
    ["Offset of field: PragueState::m_rtts_to_growth"]
        [::std::mem::offset_of!(PragueState, m_rtts_to_growth) - 188usize];
    ["Offset of field: PragueState::m_alpha"]
        [::std::mem::offset_of!(PragueState, m_alpha) - 192usize];
    ["Offset of field: PragueState::m_pacing_rate"]
        [::std::mem::offset_of!(PragueState, m_pacing_rate) - 200usize];
    ["Offset of field: PragueState::m_fractional_window"]
        [::std::mem::offset_of!(PragueState, m_fractional_window) - 208usize];
    ["Offset of field: PragueState::m_packet_burst"]
        [::std::mem::offset_of!(PragueState, m_packet_burst) - 216usize];
    ["Offset of field: PragueState::m_packet_size"]
        [::std::mem::offset_of!(PragueState, m_packet_size) - 224usize];
    ["Offset of field: PragueState::m_packet_window"]
        [::std::mem::offset_of!(PragueState, m_packet_window) - 232usize];
};
#[repr(C)]
pub struct PragueCC__bindgen_vtable(::std::os::raw::c_void);
#[repr(C)]
#[derive(Debug)]
pub struct PragueCC {
    pub vtable_: *const PragueCC__bindgen_vtable,
    pub _base: PragueState,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PragueCC"][::std::mem::size_of::<PragueCC>() - 248usize];
    ["Alignment of PragueCC"][::std::mem::align_of::<PragueCC>() - 8usize];
};
unsafe extern "C" {
    #[link_name = "\u{1}_ZN8PragueCC11get_ref_rttEv"]
    pub fn PragueCC_get_ref_rtt(this: *mut PragueCC) -> time_tp;
}
unsafe extern "C" {
    #[link_name = "\u{1}_ZN8PragueCC15get_alpha_shiftEv"]
    pub fn PragueCC_get_alpha_shift(this: *mut PragueCC) -> count_tp;
}
unsafe extern "C" {
    #[link_name = "\u{1}_ZN8PragueCC15RFC8888ReceivedEmPi"]
    pub fn PragueCC_RFC8888Received(
        this: *mut PragueCC,
        num_rtt: usize,
        pkts_rtt: *mut time_tp,
    ) -> bool;
}
unsafe extern "C" {
    #[link_name = "\u{1}_ZN8PragueCC14PacketReceivedEii"]
    pub fn PragueCC_PacketReceived(
        this: *mut PragueCC,
        timestamp: time_tp,
        echoed_timestamp: time_tp,
    ) -> bool;
}
unsafe extern "C" {
    #[link_name = "\u{1}_ZN8PragueCC11ACKReceivedEiiiibRi"]
    pub fn PragueCC_ACKReceived(
        this: *mut PragueCC,
        packets_received: count_tp,
        packets_CE: count_tp,
        packets_lost: count_tp,
        packets_sent: count_tp,
        error_L4S: bool,
        inflight: *mut count_tp,
    ) -> bool;
}
unsafe extern "C" {
    #[link_name = "\u{1}_ZN8PragueCC12DataReceivedE6ecn_tpi"]
    pub fn PragueCC_DataReceived(this: *mut PragueCC, ip_ecn: ecn_tp, packets_lost: count_tp);
}
unsafe extern "C" {
    #[link_name = "\u{1}_ZN8PragueCC20DataReceivedSequenceE6ecn_tpi"]
    pub fn PragueCC_DataReceivedSequence(
        this: *mut PragueCC,
        ip_ecn: ecn_tp,
        packet_seq_nr: count_tp,
    );
}
unsafe extern "C" {
    #[link_name = "\u{1}_ZN8PragueCC11ResetCCInfoEv"]
    pub fn PragueCC_ResetCCInfo(this: *mut PragueCC);
}
unsafe extern "C" {
    #[link_name = "\u{1}_ZN8PragueCC11GetTimeInfoERiS0_R6ecn_tp"]
    pub fn PragueCC_GetTimeInfo(
        this: *mut PragueCC,
        timestamp: *mut time_tp,
        echoed_timestamp: *mut time_tp,
        ip_ecn: *mut ecn_tp,
    );
}
unsafe extern "C" {
    #[link_name = "\u{1}_ZN8PragueCC9GetCCInfoERmRiS1_S0_"]
    pub fn PragueCC_GetCCInfo(
        this: *mut PragueCC,
        pacing_rate: *mut rate_tp,
        packet_window: *mut count_tp,
        packet_burst: *mut count_tp,
        packet_size: *mut size_tp,
    );
}
unsafe extern "C" {
    #[link_name = "\u{1}_ZN8PragueCC10GetACKInfoERiS0_S0_Rb"]
    pub fn PragueCC_GetACKInfo(
        this: *mut PragueCC,
        packets_received: *mut count_tp,
        packets_CE: *mut count_tp,
        packets_lost: *mut count_tp,
        error_L4S: *mut bool,
    );
}
unsafe extern "C" {
    #[link_name = "\u{1}_ZN8PragueCC14GetCCInfoVideoERmS0_RiS1_S0_"]
    pub fn PragueCC_GetCCInfoVideo(
        this: *mut PragueCC,
        pacing_rate: *mut rate_tp,
        frame_size: *mut size_tp,
        frame_window: *mut count_tp,
        packet_burst: *mut count_tp,
        packet_size: *mut size_tp,
    );
}
unsafe extern "C" {
    #[link_name = "\u{1}_ZN8PragueCCC1Emhimimm"]
    pub fn PragueCC_PragueCC(
        this: *mut PragueCC,
        max_packet_size: size_tp,
        fps: fps_tp,
        frame_budget: time_tp,
        init_rate: rate_tp,
        init_window: count_tp,
        min_rate: rate_tp,
        max_rate: rate_tp,
    );
}
impl PragueCC {
    #[inline]
    pub unsafe fn get_ref_rtt(&mut self) -> time_tp {
        PragueCC_get_ref_rtt(self)
    }
    #[inline]
    pub unsafe fn get_alpha_shift(&mut self) -> count_tp {
        PragueCC_get_alpha_shift(self)
    }
    #[inline]
    pub unsafe fn RFC8888Received(&mut self, num_rtt: usize, pkts_rtt: *mut time_tp) -> bool {
        PragueCC_RFC8888Received(self, num_rtt, pkts_rtt)
    }
    #[inline]
    pub unsafe fn PacketReceived(&mut self, timestamp: time_tp, echoed_timestamp: time_tp) -> bool {
        PragueCC_PacketReceived(self, timestamp, echoed_timestamp)
    }
    #[inline]
    pub unsafe fn ACKReceived(
        &mut self,
        packets_received: count_tp,
        packets_CE: count_tp,
        packets_lost: count_tp,
        packets_sent: count_tp,
        error_L4S: bool,
        inflight: *mut count_tp,
    ) -> bool {
        PragueCC_ACKReceived(
            self,
            packets_received,
            packets_CE,
            packets_lost,
            packets_sent,
            error_L4S,
            inflight,
        )
    }
    #[inline]
    pub unsafe fn DataReceived(&mut self, ip_ecn: ecn_tp, packets_lost: count_tp) {
        PragueCC_DataReceived(self, ip_ecn, packets_lost)
    }
    #[inline]
    pub unsafe fn DataReceivedSequence(&mut self, ip_ecn: ecn_tp, packet_seq_nr: count_tp) {
        PragueCC_DataReceivedSequence(self, ip_ecn, packet_seq_nr)
    }
    #[inline]
    pub unsafe fn ResetCCInfo(&mut self) {
        PragueCC_ResetCCInfo(self)
    }
    #[inline]
    pub unsafe fn GetTimeInfo(
        &mut self,
        timestamp: *mut time_tp,
        echoed_timestamp: *mut time_tp,
        ip_ecn: *mut ecn_tp,
    ) {
        PragueCC_GetTimeInfo(self, timestamp, echoed_timestamp, ip_ecn)
    }
    #[inline]
    pub unsafe fn GetCCInfo(
        &mut self,
        pacing_rate: *mut rate_tp,
        packet_window: *mut count_tp,
        packet_burst: *mut count_tp,
        packet_size: *mut size_tp,
    ) {
        PragueCC_GetCCInfo(self, pacing_rate, packet_window, packet_burst, packet_size)
    }
    #[inline]
    pub unsafe fn GetACKInfo(
        &mut self,
        packets_received: *mut count_tp,
        packets_CE: *mut count_tp,
        packets_lost: *mut count_tp,
        error_L4S: *mut bool,
    ) {
        PragueCC_GetACKInfo(self, packets_received, packets_CE, packets_lost, error_L4S)
    }
    #[inline]
    pub unsafe fn GetCCInfoVideo(
        &mut self,
        pacing_rate: *mut rate_tp,
        frame_size: *mut size_tp,
        frame_window: *mut count_tp,
        packet_burst: *mut count_tp,
        packet_size: *mut size_tp,
    ) {
        PragueCC_GetCCInfoVideo(
            self,
            pacing_rate,
            frame_size,
            frame_window,
            packet_burst,
            packet_size,
        )
    }
    #[inline]
    pub unsafe fn new(
        max_packet_size: size_tp,
        fps: fps_tp,
        frame_budget: time_tp,
        init_rate: rate_tp,
        init_window: count_tp,
        min_rate: rate_tp,
        max_rate: rate_tp,
    ) -> Self {
        let mut __bindgen_tmp = ::std::mem::MaybeUninit::uninit();
        PragueCC_PragueCC(
            __bindgen_tmp.as_mut_ptr(),
            max_packet_size,
            fps,
            frame_budget,
            init_rate,
            init_window,
            min_rate,
            max_rate,
        );
        __bindgen_tmp.assume_init()
    }
}
unsafe extern "C" {
    #[link_name = "\u{1}_ZN8PragueCCD1Ev"]
    pub fn PragueCC_PragueCC_destructor(this: *mut PragueCC);
}
unsafe extern "C" {
    #[link_name = "\u{1}_ZN8PragueCC3NowEv"]
    pub fn PragueCC_Now(this: *mut ::std::os::raw::c_void) -> time_tp;
}
